import { FC, PropsWithChildren } from "react";
import "tailwindcss/tailwind.css";
import NavLink from "./NavLink";

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="p-5">
        <header>
          <nav>
            <ul className="flex gap-5">
              <li>
                <NavLink href="/">Home</NavLink>
              </li>
              <li>
                <NavLink href="/people" exact={false}>People</NavLink>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
